# Generated by Django 3.0.6 on 2020-09-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200912_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
