# Generated by Django 3.0.6 on 2020-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
