# Generated by Django 3.0.6 on 2020-09-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20200914_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
