# Generated by Django 3.0.6 on 2020-09-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Main.Question'),
        ),
    ]
